### ISSUE TITLE
Add support for NextCloud Calendar

### ISSUE THREAD

**Issue by eiabea** [eiabea/tempea-api#33]
Currently it is only possible to use a Google Calendar as source of the heating plan.

**Comment by thelittlebug** [comment]
why no standard interface like caldav?

**Comment by eiabea** [comment]
@thelittlebug NextCloud is using the caldev interface, i just couldn't think of another caldev provider other than NextCloud :see_no_evil:

**Comment by thelittlebug** [comment]
nextcloud, google, apple mail, exchange, mailcow, ...

**Comment by eiabea** [comment]
Sorry, i meant a self hosted caldav provider :wink:

**Comment by thelittlebug** [comment]
there are hundreds available... just try to use google ;)

and google ist self hostable... i dont get your point

**Comment by eiabea** [comment]
The CalDav integration is done so far, but i ran into a NextCloud Calendar bug which would make it very hard to create all the events for different temperatures on a daily basis

https://github.com/nextcloud/calendar/issues/1159

my issue got linked to https://github.com/nextcloud/calendar/issues/7 which should resolve the issue
